### PR TITLE
Semver support

### PR DESCRIPTION
**Pull request by FaHeymann**
Hi, when using this project to sync larger repositories with many tags we found it useful to be able to filter by semver constraints and added that functionality. It is currently only implemented for the skopeo relay.

Is that something you want to support?

### CODE REVIEW

**Comment by xelalexv** [comment]
Thanks for the PR! I think filtering by semver is a great idea. This could even be extended to something like "the most recent 5 tags" and the like. However, I'm currently thinking about introducing a generic filtering mechanism (see also #16 and #22). Once this is in place, your semver constraints could become part of this. So if you're ok with this, I'd put you PR on hold for the time being.

**Comment by xelalexv** [comment]
BTW, I think you meant to say it's currently only implemented for the Docker relay, right?

**Comment by FaHeymann** [comment]
Hi,
alright thank you. I'll be looking forward to that filtering :)

The semver based filtering in this branch is currently only build into the scopeo relay, because we don't use the docker one.

**Comment by zen** [comment]
Fingers crossed, that's a must have feature!

**Comment by xelalexv** [comment]
done with PR #54

**Pull request closed without merging**
