### PR TITLE
fix: only check for gcr.io as a suffix to include gcr.io aswell as eu.gcr.io etc

### PR DESCRIPTION
**Pull request by fitz7**
This was a really small trivial change so I just went for it. Let me know if you want anything changed

seems that dregsy isn't working properly with the "gcr.io" without a region prefix due to checking the suffix ".gcr.io"

I considered checking `l.Registry == "gcr.io"` but this change seemed smaller and should work

### CODE REVIEW

**Comment by xelalexv** [comment]
Do you have an example for a _GCR_ domain for which sync does not work? The example `eu.gcr.io` from your commit comment should work, since `strings.HasSuffix("eu.gcr.io", ".gcr.io")` is already `true`.

**Comment by Fitz7** [comment]
plain `gcr.io` is the one not working

**Comment by fitz7** [comment]
should be sorted

I've added IsGCR in the same location as isDockerHub and renamed the location check function from IsGCR to IsGCP as it is checking for either.

Let me know if any other changes are required! thanks

**Pull request merged**
